### ISSUE TITLE
Plot Port Data returns a blank panel

### ISSUE THREAD

**Issue by jinweilin7325** [Geontech/docker-redhawk#4]
I am using REDHAWK IDE 2.2.0 on a centos 7.2 machine, and I can't manage to display the data plot view right. I started a SigGen in Chalkborad, the Data List returns a series of numbers but when I clicked the Plot Port Data button on a out port, a blank panel pops out. Do you have idea what is wrong here?

**Comment by jschindehette** [comment]
@jinweilin7325, I wasn't able to duplicate your issue with 2.2.0 on Centos 7.6. Which implementation of the SigGen are you using (CPP, Python, or Java)? Which output port are you plotting (float/short)? Did you happen to glance at your machine's memory utilization?

**Comment by jinweilin7325** [comment]
It turns out to be a problem of remote desktop.In the beginning,I was using the app that comes within Windows system to connect to the server . Then, when I turned to MobaXterm, the plot was properly displayed .

**Comment by jschindehette** [comment]
Ok - good to know! Thanks.
