### ISSUE TITLE
Invalid default REST_PYTHON variable

### ISSUE THREAD

**Issue by caaumen** [Geontech/docker-redhawk#5]
REST_PYTHON is defaulted to http://github.com/GeonTech/rest-python.git

This results in RPC failure,

Fix: Update all instances of http://github.com/GeonTech/rest-python.git to https://github.com/GeonTech/rest-python.git

**Comment by btgoodwin** [comment]
Thank you for calling this to our attention.  The next image push to dockerhub will be REDHAWK 2.2.3 and will contain this change.  In the mean time, locally at least, you can [follow this](https://github.com/Geontech/docker-redhawk#customizing-the-image) to rebuild the webserver container with the right URI.

**Comment by btgoodwin** [comment]
I've pushed the version 2.2.3 change to the Makefile and updated images to Dockerhub.  Thanks again!
